services:
  - type: web
    name: ecommerce-api
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y \
        postgresql-client \
        libpq-dev \
        python3-dev \
        gcc
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind=0.0.0.0:$PORT --workers=1 --log-level debug --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
      - key: POSTGRES_HOST
        fromDatabase:
          name: ecommerce-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: ecommerce-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: ecommerce-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: ecommerce-db
          property: password
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: ecommerce-db
          property: database

databases:
  - name: ecommerce-db
    databaseName: ecommerce
    plan: free
    ipAllowList: [] # allow all
